version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  backend:
    build: .
    environment:
      PORT: 8000
      TOKEN_SECRET: secret
      CALLBACK_URL: http://localhost/api/auth/callback
      KARTOFFEL_BASE_URL: https://kartoffel.example-yesodot.org
      SHRAGA_URL: https://shraga.shraga.example-yesodot.org
      ACCESS_TOKEN_NAME: rabaz-access-token
      SYSTEM_UNAVAILABLE_URL: /unavailable
